version: 2
jobs:
  install_deps:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: echo '//registry.npmjs.org/:_authToken='$NPM_TOKEN''>.npmrc
      - run: npm publish
      - run: echo '//npm.pkg.github.com/Sayegh7:_authToken='$GHUB_TOKEN''>.npmrc
      - run: npm publish
workflows:
  version: 2
  deploy:
    jobs:
      - install_deps
      - hold:
          type: approval
          requires:
            - install_deps
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
