name: CI

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v1.0.3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
      - name: Install
        run: yarn install --frozen-lockfile
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v1.0.3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
      - name: Test
        run: PERCY_TOKEN=${{ secrets.PERCY_TOKEN }} yarn test
